name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: Check formatting with black
        uses: psf/black@stable
        with:
          args: ". --check"
      
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      
      - name: Check for errors with flake8
        run: |
          python -m flake8 .
