name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black
      
      - name: Check formatting with black
        run: |
          python -m black . --check --diff
      
      - name: Check for errors with flake8
        run: |
          python -m flake8 .
