name: Docs

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        sudo apt-get install python3-tk libffms2-4
        pip install -r docs/requirements.txt

    - name: Run Sphinx
      run: make html SPHINXOPTS="-W --keep-going -n" -C docs

    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/docs'
      with:
        name: docs-latest
        path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/docs'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false

      - uses: actions/download-artifact@v2
        with:
          name: docs-latest

      - name: Commit documentation changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
